<?php

class ExtendsHelper
{
    public static function getMotivation()
    {
        // Array berisi kata-kata motivasi ala anak zaman now buat programmer
        $motivations = array(
            "Ngoding terus, cuy! Rehatnya pas deploy udah aman. 🚀",
            "Error mah biasa, yang penting jangan nyerah! 🔥",
            "Debugging itu seni, makin banyak error makin dewa lo! 💻",
            "Jangan cuma copy-paste, pahamin juga biar nggak jadi programmer robot. 🤖",
            "Kode lo adalah cerminan lo, jadi bikin yang rapi dan cakep! 🎨",
            "Gagal? Refactor lagi! Jalanin, break, fix, ulangi! 🔄",
            "Jangan takut mulai project baru, yang penting gas dulu! ⛽",
            "Banyakin ngoding biar nggak cuma jadi 'Hello World' developer! 🌍",
            "Komit di Git, jangan cuma komit di hati doang. ❤️‍🔥",
            "Skill programming itu investasi, makin rajin makin cuan! 💰",
            "Jangan cuma jago CRUD, coba explore AI, blockchain, atau cyber security! 🚀",
            "Ngoding itu kayak ngegame, semakin sering main, makin jago lo! 🎮",
            "Banyak error? Santai, otak lo lagi level up! 🧠💡",
            "Deadline mepet? Kafein + mindset pro = kelar brok! ☕💻",
            "Kode yang rapi adalah kode yang gampang dibaca, jangan jadi juru sandi! 🔑",
            "Jangan males baca dokumentasi, itu kitab sucinya programmer! 📖",
            "Skripsi belum kelar? Jangan khawatir, API dan Stack Overflow siap bantu! 😎",
            "Siapa yang bilang programmer nggak bisa kreatif? Kode lo adalah seni, bro! 🎨",
            "Nggak ada kode yang sempurna, tapi selalu bisa lebih baik! 💪",
            "Ngoding tuh kayak bercocok tanam, sabar dan terus belajar! 🌱",
            "Bisa ngoding itu satu hal, tapi bisa paham sistem adalah next level! 🚀",
            "Jangan takut belajar bahasa baru, makin banyak tools makin GG! 🔥",
            "Kalau error bikin stres, ingat! Setiap bug adalah jalan menuju wisdom. 🧘‍♂️",
            "Hidup itu kaya database, kalau salah relasi ya bakal kacau! 🏗️",
            "Semakin lo paham fundamental coding, semakin gampang lo adaptasi! 🎯",
            "Jangan kebanyakan nanya ‘ini pake framework apa?’, mending belajar dasarnya! 📚",
            "Yang penting bukan pake teknologi terbaru, tapi pake yang sesuai kebutuhan! 🛠️",
            "Di dunia coding, yang paling fleksibel yang bakal survive! 🔄",
            "Kalau stuck, coba istirahat bentar, otak juga butuh refresh! 🔄",
            "Tim solid itu bukan yang paling pinter, tapi yang paling bisa kolaborasi! 🤝",
            "Code tanpa komentar itu kaya jalan tanpa rambu, bikin pusing orang lain! 🚦",
            "Jangan cuma jago front-end, paham back-end juga biar full stack! ⚡",
            "Framework bisa ganti, tapi skill problem-solving bakal selalu kepake! 🧠",
            "Coding kayak seni bela diri, makin sering latihan makin sakti! 🥋",
            "Jangan males testing, karena bug di production bikin jantung copot! 💥",
            "Mau gaji gede? Skill up terus! Jangan stuck di comfort zone! 💰",
            "Belajar AI sekarang biar besok nggak digantikan sama AI! 🤖",
            "Ngoding tuh bukan sekedar kerjaan, tapi lifestyle! 🌟",
            "Belajar coding itu kaya farming EXP, lama-lama lo bakal OP! 🎮",
            "Jangan jadi coder yang cuma bisa googling, pahami dulu konsep dasarnya! 🔍",
            "Project personal itu penting! Jangan cuma ngerjain tugas kantor! 🚀",
            "Soft skill juga penting, jangan cuma bisa ngobrol sama terminal doang! 🗣️",
            "Salah satu skill penting programmer: googling yang efektif! 🔎",
            "Ngoding sendirian boleh, tapi jangan lupa, networking itu cuan! 💸",
            "Jangan takut mulai dari nol, semua programmer pro juga pernah newbie! 👶",
            "Dapet error? Tenang, Stack Overflow dan ChatGPT selalu ada buat lo! 🛠️",
            "Coding is fun, kalo gak fun berarti lo kurang tidur! 😂",
            "Jangan takut error, itu tandanya lo lagi belajar! 🔥",
            "Ngoding kayak puzzle, makin lo paham, makin gampang nyusunnya! 🧩",
            "Bugs itu kaya mantan, kalau nggak diselesain bakal terus kepikiran! 🤯",
            "Kode lo harus bisa dimengerti orang lain, bukan cuma lo doang! 🧐",
            "Semakin lo males refactor, semakin banyak tech debt lo! 💸",
            "Jangan cuma copy-paste, tapi coba ngerti logikanya! 🤔",
            "Gagal deploy? Tarik napas, fix bug, deploy lagi! 🔄",
            "Ngoding itu kaya sulap, dari yang nggak ada jadi ada! 🎩✨",
            "Framework bisa ganti, tapi algoritma tetep raja! 👑",
            "Pahami konsep dulu, baru pilih teknologi yang cocok! 🔍",
            "Jangan lupa backup project lo, nyesel belakangan nggak enak! 💾",
            "Debugging itu kaya nyari jarum di tumpukan jerami, tapi lo pasti nemu! 🧐",
            "Coding itu seni, jangan bikin yang asal-asalan! 🎨",
            "Bisa baca dokumentasi itu skill yang wajib! 📖",
            "Deadline mepet? Ngopi dulu biar fokus! ☕",
            "Semua coder pro dulunya newbie, jadi gas aja terus! 🚀",
            "Kalau stuck, jalan-jalan bentar, inspirasi bisa muncul kapan aja! 🌱",
            "Pahami konsep dasar sebelum ngelompat ke yang advance! 🏗️",
            "Belajar tiap hari biar nggak ketinggalan zaman! ⏳",
            "Soft skill juga penting, jangan cuma jago ngoding doang! 🗣️",
            "Full stack bukan sekadar bisa front-end dan back-end, tapi paham alurnya! 🔄",
            "Jangan cuma tau cara make, tapi juga tau cara bikin! 🏗️",
            "Tim yang kuat itu bukan yang paling jago, tapi yang paling solid! 🤝",
            "Ngoding itu life skill, bukan cuma kerjaan! 🔥",
            "Banyak error? Itu tandanya lo lagi naik level! 🆙",
            "Orang sukses bukan yang paling pintar, tapi yang paling konsisten! 🏆",
            "Jangan lari dari bug, hadapi dan selesaikan! ⚔️",
            "Belajar coding tuh kayak nge-gym, hasilnya nggak instan! 🏋️",
            "Kalau lo nggak belajar hal baru, lo bakal stuck di situ aja! 📈",
            "Coding itu tentang problem solving, bukan cuma ngetik! 🎯",
            "Nggak ada kode yang sempurna, tapi selalu ada yang lebih baik! 💡",
            "Teknologi bakal terus berkembang, jadi jangan berhenti belajar! 🔄",
            "Ngoding tanpa testing itu kaya naik motor tanpa helm, bahaya brok! 🏍️",
            "Kalau lo males belajar, siap-siap digantikan sama yang lebih rajin! 😎",
            "Jangan cuma ngerti sintaks, pahami juga konsepnya! 📚",
            "Semakin sering latihan, semakin cepet lo bisa bikin solusi! 🛠️",
            "Sukses di dunia IT butuh lebih dari sekadar skill coding, tapi juga mindset! 🏅",
            "Belajar teknologi baru itu investasi buat masa depan lo! 🚀",
            "Jangan biarin deadline bikin lo stres, atur waktu dengan bijak! ⏳",
            "Kegagalan terbesar adalah takut buat mulai! 💪",
            "Kalau lo ngerti logika, lo bisa belajar bahasa pemrograman apapun! 🔥",
            "Dunia IT itu kompetitif, yang nggak berkembang bakal ketinggalan! 🏎️",
            "Jangan males ikut komunitas, networking itu penting! 🤝",
            "Koding itu kayak memasak, kalau bahan dan resepnya bener, hasilnya mantap! 🍳",
            "Jangan cuma ikutin tren, tapi pahami kenapa tren itu muncul! 🧐",
            "Skill lo sekarang adalah hasil dari usaha lo sebelumnya! 🔄",
            "Kalau lo gagal hari ini, besok coba lagi dengan cara yang lebih baik! 🔄",
            "Ngoding tuh kayak strategi game, lo harus paham pattern-nya! 🎮"
        );

        // Pilih kata motivasi secara random
        return $motivations[array_rand($motivations)];
    }
}
